### ISSUE TITLE
Is large_files.zip corrupted ?

### ISSUE THREAD

**Issue by tintpham** [yangkevin2/naacl-2021-fudge-controlled-generation#3]
I am wondering if the large_files.zip is corrupted? I am not able to obtain the train_data and topic_human_evals folders from the large_files.zip file. Is there any way that I can get those two folders? Thanks

**Comment by yangkevin2** [comment]
Hi, 

Sorry for the delay, I must have missed the issue notif. Anyway, I tried to download it myself on MacOS. I did notice warnings such as the following when I tried to decompress using the "unzip" command:

```
warning [large_files.zip]:  4294967296 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  4294967296
  (attempting to re-compensate)
```

However, I was still able to finish decompressing and it seems like I can access things fine. What command are you using to decompress, and if it's not "unzip" could you try using that? What errors are you seeing?

**Comment by yangkevin2** [comment]
For future reference to anyone else with this issue-- I got another report that this didn't work and did some more investigation, it seems like it won't unzip on Linux for some reason, sorry. The raw files are available at https://drive.google.com/drive/folders/1GZfOGqpQxDmIfD2RvuhUQla9eX2OHUXU?usp=sharing .
