### ISSUE TITLE
Typo in iambic model padding_idx

### ISSUE THREAD

**Issue by jsu27** [yangkevin2/naacl-2021-fudge-controlled-generation#4]
Hi there, I noticed there might be a typo [here](https://github.com/yangkevin2/naacl-2021-fudge-controlled-generation/blob/master/model.py#L46):
```
elif self.iambic:
    self.gpt_embed = nn.Embedding(gpt_pad_id + 1, HIDDEN_DIM, padding_idx=0) # 0 in marian is ''
```

In all other tasks with GPT, `padding_idx=gpt_pad_id` instead of 0.

**Comment by yangkevin2** [comment]
You're right, I think it doesn't make a difference in practice but I will fix it. Thanks!
